### ISSUE TITLE
Roadmap 2.3

### ISSUE THREAD

**Issue by Refhi** [Refhi/Weda-Helper#118]
- [x] refactoriser sendToCompanion & co (gros foutoir qui risque de nous gêner pour la suite)
- [x] travailler sur le Companion et officiellement lancer la 1.3
- [x] ensuite la priorité passe à intégrer ton PR sur les pushdown https://github.com/Refhi/Weda-Helper/issues/7
- [x] Majorer les raccourcis claviers possibles #124 
- [x] #125 
- [x] #127 
- [x] #106 
- [x] #132

**Comment by Refhi** [comment]
refactory de sendToCompanion et startPrinting fait ! (gros boulot... 6-7h ? c'est maintenant lisible, simple et maintenable je pense)

**Comment by Refhi** [comment]
Vraiment top le système de raccourcis claviers !
Je teste ça demain en situation réelle, mais c'est bluffant.

Je rajoute #124 avant de valider la 2.3, et on est bon !
La base me parait beaucoup plus souple et solide pour assurer la suite de WH ^^ C'est agréable de voir toutes ces avancées

Faudra que je bosse sur la roadmap de la 2.4,

**Comment by Refhi** [comment]
Ahhh... mais pourquoi plus on progresse plus y'a de tickets à résoudre >.<
Elle nous en fait baver cette 2.3 !
Bon, je viens de valider #128  je vérifie que tout est ok demain

**Comment by Abeldvlpr** [comment]
Ca avance, je t'ai fait les PR pour #124 et #127, je les test demain au cabinet

**Comment by Abeldvlpr** [comment]
Attention le fix a cassé les raccourcis du menu W

**Comment by Abeldvlpr** [comment]
Et il manque `hotkeys.filter = function(event){
        return true; // Permet d'utiliser les raccourcis depuis un input ou un textarea
}`

**Comment by Refhi** [comment]
ok, je regarde de suite :)

**Comment by Refhi** [comment]
> Et il manque `hotkeys.filter = function(event){ return true; // Permet d'utiliser les raccourcis depuis un input ou un textarea }`

Je viens de tester et il semble que ça fonctionne tout de même, je peux te laisser regarder ?

**Comment by Refhi** [comment]
> Attention le fix a cassé les raccourcis du menu W. Non au temps pour moi, cela fonctionne toujours mais ca ne récupère pas les raccourcis par défaut

Arg. J'ai du supprimer un bout de code important au moment d'un merge...

Je sais que tu avais déjà bossé là-dessus, est-ce que je peux te laisser corriger le pb stp ? :-/ #118

**Comment by Abeldvlpr** [comment]
> > Attention le fix a cassé les raccourcis du menu W. Non au temps pour moi, cela fonctionne toujours mais ca ne récupère pas les raccourcis par défaut
> 
> Arg. J'ai du supprimer un bout de code important au moment d'un merge...
> 
> Je sais que tu avais déjà bossé là-dessus, est-ce que je peux te laisser corriger le pb stp ? :-/ #118

Je m'en occupe

**Comment by Abeldvlpr** [comment]
Par contre les raccourcis ne fonctionnent pas du tout chez moi depuis une iframe en prenant tes derniers commits..

**Comment by Refhi** [comment]
> Par contre les raccourcis ne fonctionnent pas du tout chez moi depuis une iframe en prenant tes derniers commits..

Arg... chromium linus ras... je teste sous windows

**Comment by Abeldvlpr** [comment]
Ca me les ajoute bien dans chaque iframe mais ca déclenche rien du tout si le focus est sur l'une d'entre elles...

**Comment by Abeldvlpr** [comment]
Ok c'est une question de délai sur `afterMutations()`, mon Mac est un peu vieux, ca fonctionne qu'à partir de 200 de délai

**Comment by Abeldvlpr** [comment]
> > Et il manque `hotkeys.filter = function(event){ return true; // Permet d'utiliser les raccourcis depuis un input ou un textarea }`
> 
> Je viens de tester et il semble que ça fonctionne tout de même, je peux te laisser regarder ?

En effet, tout marche sans...

**Comment by Refhi** [comment]
> Ok c'est une question de délai sur `afterMutations()`, mon Mac est un peu vieux, ca fonctionne qu'à partir de 200 de délai

On met peut-être 300ms histoire d'être large ?
J'imagine mal quelqu'un être gêné par 200ms de lag 😅

Là je vais tester l'upload et la 2.3 in situ sur une semaine et ensuite je balance.
En parallèle je vais ouvrir une branche dédiée pour la 2.4 et commencer à bosser la roadmap

**Comment by Abeldvlpr** [comment]
Ça me semble bien avec 300 ms en effet. Je te laisse faire la release ou me dire à quel commit tu figes la 2.3 et je la teste sur la semaine au cabinet !

**Comment by Refhi** [comment]
Fait !

En ce qui me concerne la 2.3 est bouclée, je viens de faire un commit pour la RC1

On teste une semaine, on fait les éventuels correctifs, et on publie ça !

**Comment by Refhi** [comment]
@Abeldvlpr j'ai fait quelques jours de test et ça me paraît solide.
Si c'est OK de ton côté, je publie demain soir ? 🤔

**Comment by Abeldvlpr** [comment]
Pas eu de soucis particulier non plus sur la semaine au cabinet !
